[package]
name = "shared"
version = "0.3.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { workspace = true }
soroban-auth = { workspace = true }

[features]
test_mode = []